project:
  type: website

website:
  title: "Vaishh's Data blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Vaishhh125
      - icon: linkedin
        href: https://www.linkedin.com/in/vaishnaviamuda12/
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



