project:
  type: website

website:
  title: "Vaishnavi's Data blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Vaishhh125
        text: GitHub
      - icon: linkedIn
        href: https://www.linkedin.com/in/vaishnaviamuda12/
        text: LinkedIn
format:
  html:
    css: styles.css
    toc: true



